### ISSUE TITLE
Ipv4Cidr::from_str from exemple to easy-upnp not working

### ISSUE THREAD

**Issue by hinteor** [FloGa/upnp-daemon#5] opened 2024-04-01 20:38 UTC
I tried to use `address: Some(Ipv4Cidr::from_str("192.168.0.10/24")?)` , but got "expected `cidr_utils::cidr::v4::ipv4_cidr::Ipv4Cidr`, found `Ipv4Cidr` " error 
What have I done wrong ?

**Comment by FloGa** [comment] 2024-04-01 22:00
Hi there, thanks for reaching out! I'm not in front of a computer right now, I can check more deeply next weekend. But it sounds to me like a wrong import or an incompatible version of `cidr_utils`. Can you please share a complete minimal example, including imports?

**Comment by hinteor** [comment] 2024-04-02 10:03
I tried an example from here https://docs.rs/easy-upnp/latest/easy_upnp/ and got an error 
`
error[E0599]: no function or associated item named `from_str` found for struct `Ipv4Cidr` in the current scope
   --> src\main.rs:16:33
    |
16  |         address: Some(Ipv4Cidr::from_str("192.168.0.10/24")?),
    |                                 ^^^^^^^^ function or associated item not found in `Ipv4Cidr`
    |
`
You indicated dependencies cidr-utils 0.5.10 and higher . Maybe you should specify a specific version?

**Comment by hinteor** [comment] 2024-04-02 10:10
I checked on version cidr-utils  0.5.10, automatically installed 0.5.11 and I got an error when starting up:

```
thread 'main' panicked at C:\Users\hinte\.cargo\registry\src\index.crates.io-6f17d22bba15001f\easy-upnp-0.1.1\src\lib.rs:156:10:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\core\src\panicking.rs:72
   2: core::panicking::panic
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\core\src\panicking.rs:144
   3: enum2$<core::option::Option<tuple$<igd::gateway::Gateway,enum2$<core::net::socket_addr::SocketAddr> > > >::unwrap<tuple$<igd::gateway::Gateway,enum2$<core::net::socket_addr::SocketAddr> > >
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\core\src\option.rs:931
   4: easy_upnp::find_gateway_and_addr
             at C:\Users\hinte\.cargo\registry\src\index.crates.io-6f17d22bba15001f\easy-upnp-0.1.1\src\lib.rs:117
   5: easy_upnp::get_gateway_and_address_from_options
             at C:\Users\hinte\.cargo\registry\src\index.crates.io-6f17d22bba15001f\easy-upnp-0.1.1\src\lib.rs:178
   6: easy_upnp::UpnpConfig::add_port
             at C:\Users\hinte\.cargo\registry\src\index.crates.io-6f17d22bba15001f\easy-upnp-0.1.1\src\lib.rs:289
   7: easy_upnp::add_ports<array$<easy_upnp::UpnpConfig,3> >
             at C:\Users\hinte\.cargo\registry\src\index.crates.io-6f17d22bba15001f\easy-upnp-0.1.1\src\lib.rs:331
   8: test_easy_upnp::main
             at .\src\main.rs:39
   9: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global> > > (*)(),tuple$<> >
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\test-easy-upnp.exe` (exit code: 101)
```

(Update by FloGa: Wrap output into code block for better readability.)

**Comment by FloGa** [comment] 2024-04-02 10:13
Specifying exact versions is not a good practice. After all, that's what semantic versioning should take care of if all respective developers respect it.

Please give me a few days, latest at the weekend I can take a look what's happening. When I released it, it definitely worked because I have this exact code in a runnable statement in the documentation. The compiler would have alarmed me if it didn't work. So maybe it's really a problem with a newer version of a dependency.

**Comment by FloGa** [comment] 2024-04-06 14:00
So, I looked into this and I see two distinct issues.

The first issue, that you are unable to create a `UpnpConfig` object because `Ipv4Cidr::from_str` could not be found, I cannot reproduce. I tried with Linux and Windows machines, just in case we have a mismatch here. But I still suspect a version mismatch somewhere. So maybe I'll re-export Ipv4Cidr and suggest using this instead of a custom-imported one. I'll look into this and check best practices, and I'll keep you updated on this one.

Now, the second issue is what you posted with the `RUST_BACKTRACE`. This issue does not come from some conversion, but it comes from the `add_ports` method, or more accurately from the `igd::search_gateway` method. This method will return an error if no gateway could be found. It is of course very bad practice of me to use `unwrap` and friends in a library, I should rather propagate the Result. I will take this action as a "fix" for this issue.

For you to get your example up and running, you need to use an IP address that is actually in the address range of the router you want to target. My router sits at `192.168.0.1`, this is why the address `192.168.0.10` (my desktop computer) is able to reach it. If your router however sits for example in `192.168.178.1` (AVM/FritzBox routers tend to use this address), you will not find it in the IP range `192.168.0.10/24` (which contains all addresses between `192.168.0.1` and `192.168.0.255`). Instead try to use `192.168.0.10/16` (which covers `192.168.0.1` to `192.168.255.255`), or even better, use a machine's IP address that actually lives in the same network as your router.

**Comment by FloGa** [comment] 2024-04-07 13:38
Changes in the new release:

- Errors in easy-upnp are now properly propagated instead of using `unwrap`. Where it makes sense, `Result`s are used so a caller can handle errors accordingly.
- The `Ipv4Cidr` struct is now re-exported, to avoid mismatching dependency problems. Check out the updated documentation on how to use it. It is just a matter of changing the `use` statement, you don't need to manually add `cidr-utils` as dependency anymore.

If you still have questions or problems, don't hesitate to come back here!

**Comment by FloGa** [comment] 2024-04-19 20:11
Last update was two weeks ago. I'll close this issue for now. If you still need support here, don't hesitate to open it again!

**Closed as completed by FloGa** 2024-04-19 20:11 UTC
